services:
  - type: web
    name: kathape
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 240 --workers 1 --threads 2 --worker-class=gthread --log-level debug
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kathape-db
          property: connectionString
      - key: FLASK_DEBUG
        value: "1"
      - key: RENDER
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER_DASHBOARD_LIMIT
        value: "3"
      - key: RENDER_QUERY_LIMIT
        value: "5"
      - key: RENDER_EMERGENCY_LOGIN
        value: "true"
      - key: SECRET_KEY
        value: fc36290a52f89c1c92655b7d22b198e4
      - key: UPLOAD_FOLDER
        value: static/uploads
      - key: PORT
        value: 10000
      - key: FLASK_APP
        value: "flask_app.py"
      - key: DB_QUERY_TIMEOUT
        value: "30"

databases:
  - name: kathape-db
    databaseName: kathape
    user: kathape_admin 