services:
  - type: web
    name: kathape
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_bridge:application --timeout 60 --no-sendfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production 