services:
  - type: web
    name: kathape
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bridge:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11 